### ISSUE TITLE
Not working on kirby 3.3.0

### ISSUE THREAD

**Issue by CydGoblin** [rasteiner/k3-maxpixels-option#3]
I tried this plugins with a new install of the new kirby version 3.3.0 but it doesn't work. Files are uploaded on their original size.

**Comment by rasteiner** [comment]
Hello, 
sorry for the long wait. 

I've tried on 3.3.0 and 3.3.3 and it seems to work here. 
Some questions: 
 - what browser are you using? 
 - have you actually put the `maxpixels` option in your section blueprint? The plugin does **not** fallback to a "factory default" maximum image size. So you need to actually define a `maxpixels` option on each files section. Like this:
   ```
   my_image_section:
     type: files
     maxpixels: 2000000
   ```
 - how big is the image? Do smaller images (and even smaller `maxpixels` values) work? The plugin uses an html5 `canvas` to resize the image, I guess this could fail if the browser refuses to allocate enough memory for a **very large** image.

**Comment by CydGoblin** [comment]
It's working now but I'm working on something different now so I'm not sure whats different from before. If i find anything else I'll post again.
